package com.company;

import java.util.ArrayList;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {

        System.out.print("Indtast postnummer: ");
        Scanner input = new Scanner(System.in);
        int postnummer = input.nextInt();

        ArrayList<PostInfo> listeMedPostInfo = new ArrayList<>();

        listeMedPostInfo.add(new PostInfo(	800	,"	Høje Taastrup	"));
        listeMedPostInfo.add(new PostInfo(	900	,"	København C	"));
        listeMedPostInfo.add(new PostInfo(	917	,"	Københavns Pakkecent	"));
        listeMedPostInfo.add(new PostInfo(	960	,"	Udland	"));
        listeMedPostInfo.add(new PostInfo(	999	,"	København C	"));
        listeMedPostInfo.add(new PostInfo(	1000	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1050	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1051	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1052	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1053	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1054	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1055	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1056	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1057	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1058	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1059	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1060	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1061	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1062	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1063	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1064	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1065	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1066	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1067	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1068	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1069	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1070	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1071	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1072	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1073	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1074	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1092	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1093	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1095	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1098	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1100	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1101	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1102	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1103	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1104	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1105	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1106	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1107	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1110	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1111	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1112	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1113	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1114	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1115	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1116	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1117	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1118	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1119	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1120	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1121	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1122	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1123	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1124	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1125	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1126	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1127	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1128	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1129	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1130	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1131	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1140	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1147	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1148	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1150	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1151	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1152	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1153	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1154	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1155	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1156	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1157	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1158	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1159	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1160	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1161	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1162	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1164	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1165	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1166	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1167	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1168	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1169	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1170	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1171	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1172	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1173	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1174	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1175	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1200	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1201	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1202	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1203	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1204	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1205	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1206	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1207	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1208	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1209	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1210	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1211	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1213	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1214	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1215	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1216	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1217	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1218	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1219	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1220	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1221	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1240	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1250	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1251	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1253	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1254	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1255	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1256	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1257	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1259	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1260	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1261	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1263	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1264	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1265	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1266	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1267	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1268	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1270	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1271	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1291	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1300	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1301	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1302	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1303	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1304	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1306	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1307	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1308	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1309	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1310	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1311	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1312	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1313	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1314	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1315	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1316	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1317	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1318	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1319	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1320	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1321	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1322	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1323	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1324	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1325	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1326	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1327	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1328	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1329	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1350	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1352	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1353	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1354	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1355	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1356	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1357	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1358	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1359	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1360	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1361	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1362	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1363	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1364	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1365	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1366	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1367	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1368	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1369	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1370	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1371	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1400	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1401	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1402	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1403	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1406	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1407	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1408	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1409	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1410	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1411	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1412	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1413	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1414	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1415	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1416	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1417	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1418	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1419	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1420	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1421	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1422	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1423	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1424	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1425	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1426	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1427	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1428	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1429	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1430	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1431	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1432	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1433	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1434	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1435	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1436	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1437	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1438	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1439	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1440	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1441	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1448	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1450	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1451	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1452	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1453	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1454	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1455	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1456	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1457	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1458	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1459	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1460	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1462	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1463	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1464	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1466	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1467	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1468	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1470	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1471	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1472	,"	København K	"));
        listeMedPostInfo.add(new PostInfo(	1500	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1513	,"	Centraltastning	"));
        listeMedPostInfo.add(new PostInfo(	1532	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1533	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1550	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1551	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1552	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1553	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1554	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1555	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1556	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1557	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1558	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1559	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1560	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1561	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1562	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1563	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1564	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1566	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1567	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1568	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1569	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1570	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1571	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1572	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1573	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1574	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1575	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1576	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1577	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1592	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1599	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1600	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1601	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1602	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1603	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1604	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1606	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1607	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1608	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1609	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1610	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1611	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1612	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1613	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1614	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1615	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1616	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1617	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1618	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1619	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1620	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1621	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1622	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1623	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1624	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1630	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1631	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1632	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1633	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1634	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1635	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1650	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1651	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1652	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1653	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1654	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1655	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1656	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1657	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1658	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1659	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1660	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1661	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1662	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1663	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1664	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1665	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1666	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1667	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1668	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1669	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1670	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1671	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1672	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1673	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1674	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1675	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1676	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1677	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1699	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1700	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1701	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1702	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1703	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1704	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1705	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1706	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1707	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1708	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1709	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1710	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1711	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1712	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1714	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1715	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1716	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1717	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1718	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1719	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1720	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1721	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1722	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1723	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1724	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1725	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1726	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1727	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1728	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1729	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1730	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1731	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1732	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1733	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1734	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1735	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1736	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1737	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1738	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1739	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1749	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1750	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1751	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1752	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1753	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1754	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1755	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1756	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1757	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1758	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1759	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1760	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1761	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1762	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1763	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1764	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1765	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1766	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1770	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1771	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1772	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1773	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1774	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1775	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1777	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1780	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1785	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1786	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1787	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1790	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1799	,"	København V	"));
        listeMedPostInfo.add(new PostInfo(	1800	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1801	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1802	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1803	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1804	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1805	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1806	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1807	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1808	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1809	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1810	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1811	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1812	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1813	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1814	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1815	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1816	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1817	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1818	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1819	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1820	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1822	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1823	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1824	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1825	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1826	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1827	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1828	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1829	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1850	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1851	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1852	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1853	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1854	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1855	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1856	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1857	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1860	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1861	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1862	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1863	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1864	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1865	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1866	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1867	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1868	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1870	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1871	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1872	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1873	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1874	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1875	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1876	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1877	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1878	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1879	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1900	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1901	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1902	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1903	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1904	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1905	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1906	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1908	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1909	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1910	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1911	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1912	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1913	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1914	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1915	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1916	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1917	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1920	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1921	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1922	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1923	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1924	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1925	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1926	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1927	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1928	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1950	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1951	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1952	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1953	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1954	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1955	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1956	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1957	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1958	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1959	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1960	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1961	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1962	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1963	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1964	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1965	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1966	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1967	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1970	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1971	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1972	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1973	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	1974	,"	Frederiksberg C	"));
        listeMedPostInfo.add(new PostInfo(	2000	,"	Frederiksberg	"));
        listeMedPostInfo.add(new PostInfo(	2100	,"	København Ø	"));
        listeMedPostInfo.add(new PostInfo(	2150	,"	Nordhavn	"));
        listeMedPostInfo.add(new PostInfo(	2200	,"	København N	"));
        listeMedPostInfo.add(new PostInfo(	2300	,"	København S	"));
        listeMedPostInfo.add(new PostInfo(	2400	,"	København NV	"));
        listeMedPostInfo.add(new PostInfo(	2450	,"	København SV	"));
        listeMedPostInfo.add(new PostInfo(	2500	,"	Valby	"));
        listeMedPostInfo.add(new PostInfo(	2600	,"	Glostrup	"));
        listeMedPostInfo.add(new PostInfo(	2605	,"	Brøndby	"));
        listeMedPostInfo.add(new PostInfo(	2610	,"	Rødovre	"));
        listeMedPostInfo.add(new PostInfo(	2620	,"	Albertslund	"));
        listeMedPostInfo.add(new PostInfo(	2625	,"	Vallensbæk	"));
        listeMedPostInfo.add(new PostInfo(	2630	,"	Taastrup	"));
        listeMedPostInfo.add(new PostInfo(	2635	,"	Ishøj	"));
        listeMedPostInfo.add(new PostInfo(	2640	,"	Hedehusene	"));
        listeMedPostInfo.add(new PostInfo(	2650	,"	Hvidovre	"));
        listeMedPostInfo.add(new PostInfo(	2660	,"	Brøndby Strand	"));
        listeMedPostInfo.add(new PostInfo(	2665	,"	Vallensbæk Strand	"));
        listeMedPostInfo.add(new PostInfo(	2670	,"	Greve	"));
        listeMedPostInfo.add(new PostInfo(	2680	,"	Solrød Strand	"));
        listeMedPostInfo.add(new PostInfo(	2690	,"	Karlslunde	"));
        listeMedPostInfo.add(new PostInfo(	2700	,"	Brønshøj	"));
        listeMedPostInfo.add(new PostInfo(	2720	,"	Vanløse	"));
        listeMedPostInfo.add(new PostInfo(	2730	,"	Herlev	"));
        listeMedPostInfo.add(new PostInfo(	2740	,"	Skovlunde	"));
        listeMedPostInfo.add(new PostInfo(	2750	,"	Ballerup	"));
        listeMedPostInfo.add(new PostInfo(	2760	,"	Måløv	"));
        listeMedPostInfo.add(new PostInfo(	2765	,"	Smørum	"));
        listeMedPostInfo.add(new PostInfo(	2770	,"	Kastrup	"));
        listeMedPostInfo.add(new PostInfo(	2791	,"	Dragør	"));
        listeMedPostInfo.add(new PostInfo(	2800	,"	Kongens Lyngby	"));
        listeMedPostInfo.add(new PostInfo(	2820	,"	Gentofte	"));
        listeMedPostInfo.add(new PostInfo(	2830	,"	Virum	"));
        listeMedPostInfo.add(new PostInfo(	2840	,"	Holte	"));
        listeMedPostInfo.add(new PostInfo(	2850	,"	Nærum	"));
        listeMedPostInfo.add(new PostInfo(	2860	,"	Søborg	"));
        listeMedPostInfo.add(new PostInfo(	2870	,"	Dyssegård	"));
        listeMedPostInfo.add(new PostInfo(	2880	,"	Bagsværd	"));
        listeMedPostInfo.add(new PostInfo(	2900	,"	Hellerup	"));
        listeMedPostInfo.add(new PostInfo(	2920	,"	Charlottenlund	"));
        listeMedPostInfo.add(new PostInfo(	2930	,"	Klampenborg	"));
        listeMedPostInfo.add(new PostInfo(	2942	,"	Skodsborg	"));
        listeMedPostInfo.add(new PostInfo(	2950	,"	Vedbæk	"));
        listeMedPostInfo.add(new PostInfo(	2960	,"	Rungsted Kyst	"));
        listeMedPostInfo.add(new PostInfo(	2970	,"	Hørsholm	"));
        listeMedPostInfo.add(new PostInfo(	2980	,"	Kokkedal	"));
        listeMedPostInfo.add(new PostInfo(	2990	,"	Nivå	"));
        listeMedPostInfo.add(new PostInfo(	3000	,"	Helsingør	"));
        listeMedPostInfo.add(new PostInfo(	3050	,"	Humlebæk	"));
        listeMedPostInfo.add(new PostInfo(	3060	,"	Espergærde	"));
        listeMedPostInfo.add(new PostInfo(	3070	,"	Snekkersten	"));
        listeMedPostInfo.add(new PostInfo(	3080	,"	Tikøb	"));
        listeMedPostInfo.add(new PostInfo(	3100	,"	Hornbæk	"));
        listeMedPostInfo.add(new PostInfo(	3120	,"	Dronningmølle	"));
        listeMedPostInfo.add(new PostInfo(	3140	,"	Ålsgårde	"));
        listeMedPostInfo.add(new PostInfo(	3150	,"	Hellebæk	"));
        listeMedPostInfo.add(new PostInfo(	3200	,"	Helsinge	"));
        listeMedPostInfo.add(new PostInfo(	3210	,"	Vejby	"));
        listeMedPostInfo.add(new PostInfo(	3220	,"	Tisvildeleje	"));
        listeMedPostInfo.add(new PostInfo(	3230	,"	Græsted	"));
        listeMedPostInfo.add(new PostInfo(	3250	,"	Gilleleje	"));
        listeMedPostInfo.add(new PostInfo(	3300	,"	Frederiksværk	"));
        listeMedPostInfo.add(new PostInfo(	3310	,"	Ølsted	"));
        listeMedPostInfo.add(new PostInfo(	3320	,"	Skævinge	"));
        listeMedPostInfo.add(new PostInfo(	3330	,"	Gørløse	"));
        listeMedPostInfo.add(new PostInfo(	3360	,"	Liseleje	"));
        listeMedPostInfo.add(new PostInfo(	3370	,"	Melby	"));
        listeMedPostInfo.add(new PostInfo(	3390	,"	Hundested	"));
        listeMedPostInfo.add(new PostInfo(	3400	,"	Hillerød	"));
        listeMedPostInfo.add(new PostInfo(	3450	,"	Allerød	"));
        listeMedPostInfo.add(new PostInfo(	3460	,"	Birkerød	"));
        listeMedPostInfo.add(new PostInfo(	3480	,"	Fredensborg	"));
        listeMedPostInfo.add(new PostInfo(	3490	,"	Kvistgård	"));
        listeMedPostInfo.add(new PostInfo(	3500	,"	Værløse	"));
        listeMedPostInfo.add(new PostInfo(	3520	,"	Farum	"));
        listeMedPostInfo.add(new PostInfo(	3540	,"	Lynge	"));
        listeMedPostInfo.add(new PostInfo(	3550	,"	Slangerup	"));
        listeMedPostInfo.add(new PostInfo(	3600	,"	Frederikssund	"));
        listeMedPostInfo.add(new PostInfo(	3630	,"	Jægerspris	"));
        listeMedPostInfo.add(new PostInfo(	3650	,"	Ølstykke	"));
        listeMedPostInfo.add(new PostInfo(	3660	,"	Stenløse	"));
        listeMedPostInfo.add(new PostInfo(	3670	,"	Veksø Sjælland	"));
        listeMedPostInfo.add(new PostInfo(	3700	,"	Rønne	"));
        listeMedPostInfo.add(new PostInfo(	3720	,"	Aakirkeby	"));
        listeMedPostInfo.add(new PostInfo(	3730	,"	Nexø	"));
        listeMedPostInfo.add(new PostInfo(	3740	,"	Svaneke	"));
        listeMedPostInfo.add(new PostInfo(	3751	,"	Østermarie	"));
        listeMedPostInfo.add(new PostInfo(	3760	,"	Gudhjem	"));
        listeMedPostInfo.add(new PostInfo(	3770	,"	Allinge	"));
        listeMedPostInfo.add(new PostInfo(	3782	,"	Klemensker	"));
        listeMedPostInfo.add(new PostInfo(	3790	,"	Hasle	"));
        listeMedPostInfo.add(new PostInfo(	4000	,"	Roskilde	"));
        listeMedPostInfo.add(new PostInfo(	4030	,"	Tune	"));
        listeMedPostInfo.add(new PostInfo(	4040	,"	Jyllinge	"));
        listeMedPostInfo.add(new PostInfo(	4050	,"	Skibby	"));
        listeMedPostInfo.add(new PostInfo(	4060	,"	Kirke Såby	"));
        listeMedPostInfo.add(new PostInfo(	4070	,"	Kirke Hyllinge	"));
        listeMedPostInfo.add(new PostInfo(	4100	,"	Ringsted	"));
        listeMedPostInfo.add(new PostInfo(	4130	,"	Viby Sjælland	"));
        listeMedPostInfo.add(new PostInfo(	4140	,"	Borup	"));
        listeMedPostInfo.add(new PostInfo(	4160	,"	Herlufmagle	"));
        listeMedPostInfo.add(new PostInfo(	4171	,"	Glumsø	"));
        listeMedPostInfo.add(new PostInfo(	4173	,"	Fjenneslev	"));
        listeMedPostInfo.add(new PostInfo(	4174	,"	Jystrup Midtsj	"));
        listeMedPostInfo.add(new PostInfo(	4180	,"	Sorø	"));
        listeMedPostInfo.add(new PostInfo(	4190	,"	Munke Bjergby	"));
        listeMedPostInfo.add(new PostInfo(	4200	,"	Slagelse	"));
        listeMedPostInfo.add(new PostInfo(	4220	,"	Korsør	"));
        listeMedPostInfo.add(new PostInfo(	4230	,"	Skælskør	"));
        listeMedPostInfo.add(new PostInfo(	4241	,"	Vemmelev	"));
        listeMedPostInfo.add(new PostInfo(	4242	,"	Boeslunde	"));
        listeMedPostInfo.add(new PostInfo(	4243	,"	Rude	"));
        listeMedPostInfo.add(new PostInfo(	4250	,"	Fuglebjerg	"));
        listeMedPostInfo.add(new PostInfo(	4261	,"	Dalmose	"));
        listeMedPostInfo.add(new PostInfo(	4262	,"	Sandved	"));
        listeMedPostInfo.add(new PostInfo(	4270	,"	Høng	"));
        listeMedPostInfo.add(new PostInfo(	4281	,"	Gørlev	"));
        listeMedPostInfo.add(new PostInfo(	4291	,"	Ruds Vedby	"));
        listeMedPostInfo.add(new PostInfo(	4293	,"	Dianalund	"));
        listeMedPostInfo.add(new PostInfo(	4295	,"	Stenlille	"));
        listeMedPostInfo.add(new PostInfo(	4296	,"	Nyrup	"));
        listeMedPostInfo.add(new PostInfo(	4300	,"	Holbæk	"));
        listeMedPostInfo.add(new PostInfo(	4320	,"	Lejre	"));
        listeMedPostInfo.add(new PostInfo(	4330	,"	Hvalsø	"));
        listeMedPostInfo.add(new PostInfo(	4340	,"	Tølløse	"));
        listeMedPostInfo.add(new PostInfo(	4350	,"	Ugerløse	"));
        listeMedPostInfo.add(new PostInfo(	4360	,"	Kirke Eskilstrup	"));
        listeMedPostInfo.add(new PostInfo(	4370	,"	Store Merløse	"));
        listeMedPostInfo.add(new PostInfo(	4390	,"	Vipperød	"));
        listeMedPostInfo.add(new PostInfo(	4400	,"	Kalundborg	"));
        listeMedPostInfo.add(new PostInfo(	4420	,"	Regstrup	"));
        listeMedPostInfo.add(new PostInfo(	4440	,"	Mørkøv	"));
        listeMedPostInfo.add(new PostInfo(	4450	,"	Jyderup	"));
        listeMedPostInfo.add(new PostInfo(	4460	,"	Snertinge	"));
        listeMedPostInfo.add(new PostInfo(	4470	,"	Svebølle	"));
        listeMedPostInfo.add(new PostInfo(	4480	,"	Store Fuglede	"));
        listeMedPostInfo.add(new PostInfo(	4490	,"	Jerslev Sjælland	"));
        listeMedPostInfo.add(new PostInfo(	4500	,"	Nykøbing Sj	"));
        listeMedPostInfo.add(new PostInfo(	4520	,"	Svinninge	"));
        listeMedPostInfo.add(new PostInfo(	4532	,"	Gislinge	"));
        listeMedPostInfo.add(new PostInfo(	4534	,"	Hørve	"));
        listeMedPostInfo.add(new PostInfo(	4540	,"	Fårevejle	"));
        listeMedPostInfo.add(new PostInfo(	4550	,"	Asnæs	"));
        listeMedPostInfo.add(new PostInfo(	4560	,"	Vig	"));
        listeMedPostInfo.add(new PostInfo(	4571	,"	Grevinge	"));
        listeMedPostInfo.add(new PostInfo(	4572	,"	Nørre Asmindrup	"));
        listeMedPostInfo.add(new PostInfo(	4573	,"	Højby	"));
        listeMedPostInfo.add(new PostInfo(	4581	,"	Rørvig	"));
        listeMedPostInfo.add(new PostInfo(	4583	,"	Sjællands Odde	"));
        listeMedPostInfo.add(new PostInfo(	4591	,"	Føllenslev	"));
        listeMedPostInfo.add(new PostInfo(	4592	,"	Sejerø	"));
        listeMedPostInfo.add(new PostInfo(	4593	,"	Eskebjerg	"));
        listeMedPostInfo.add(new PostInfo(	4600	,"	Køge	"));
        listeMedPostInfo.add(new PostInfo(	4621	,"	Gadstrup	"));
        listeMedPostInfo.add(new PostInfo(	4622	,"	Havdrup	"));
        listeMedPostInfo.add(new PostInfo(	4623	,"	Lille Skensved	"));
        listeMedPostInfo.add(new PostInfo(	4632	,"	Bjæverskov	"));
        listeMedPostInfo.add(new PostInfo(	4640	,"	Faxe	"));
        listeMedPostInfo.add(new PostInfo(	4652	,"	Hårlev	"));
        listeMedPostInfo.add(new PostInfo(	4653	,"	Karise	"));
        listeMedPostInfo.add(new PostInfo(	4654	,"	Faxe Ladeplads	"));
        listeMedPostInfo.add(new PostInfo(	4660	,"	Store Heddinge	"));
        listeMedPostInfo.add(new PostInfo(	4671	,"	Strøby	"));
        listeMedPostInfo.add(new PostInfo(	4672	,"	Klippinge	"));
        listeMedPostInfo.add(new PostInfo(	4673	,"	Rødvig Stevns	"));
        listeMedPostInfo.add(new PostInfo(	4681	,"	Herfølge	"));
        listeMedPostInfo.add(new PostInfo(	4682	,"	Tureby	"));
        listeMedPostInfo.add(new PostInfo(	4683	,"	Rønnede	"));
        listeMedPostInfo.add(new PostInfo(	4684	,"	Holmegaard	"));
        listeMedPostInfo.add(new PostInfo(	4690	,"	Haslev	"));
        listeMedPostInfo.add(new PostInfo(	4700	,"	Næstved	"));
        listeMedPostInfo.add(new PostInfo(	4720	,"	Præstø	"));
        listeMedPostInfo.add(new PostInfo(	4733	,"	Tappernøje	"));
        listeMedPostInfo.add(new PostInfo(	4735	,"	Mern	"));
        listeMedPostInfo.add(new PostInfo(	4736	,"	Karrebæksminde	"));
        listeMedPostInfo.add(new PostInfo(	4750	,"	Lundby	"));
        listeMedPostInfo.add(new PostInfo(	4760	,"	Vordingborg	"));
        listeMedPostInfo.add(new PostInfo(	4771	,"	Kalvehave	"));
        listeMedPostInfo.add(new PostInfo(	4772	,"	Langebæk	"));
        listeMedPostInfo.add(new PostInfo(	4773	,"	Stensved	"));
        listeMedPostInfo.add(new PostInfo(	4780	,"	Stege	"));
        listeMedPostInfo.add(new PostInfo(	4791	,"	Borre	"));
        listeMedPostInfo.add(new PostInfo(	4792	,"	Askeby	"));
        listeMedPostInfo.add(new PostInfo(	4793	,"	Bogø By	"));
        listeMedPostInfo.add(new PostInfo(	4800	,"	Nykøbing F	"));
        listeMedPostInfo.add(new PostInfo(	4840	,"	Nørre Alslev	"));
        listeMedPostInfo.add(new PostInfo(	4850	,"	Stubbekøbing	"));
        listeMedPostInfo.add(new PostInfo(	4862	,"	Guldborg	"));
        listeMedPostInfo.add(new PostInfo(	4863	,"	Eskilstrup	"));
        listeMedPostInfo.add(new PostInfo(	4871	,"	Horbelev	"));
        listeMedPostInfo.add(new PostInfo(	4872	,"	Idestrup	"));
        listeMedPostInfo.add(new PostInfo(	4873	,"	Væggerløse	"));
        listeMedPostInfo.add(new PostInfo(	4874	,"	Gedser	"));
        listeMedPostInfo.add(new PostInfo(	4880	,"	Nysted	"));
        listeMedPostInfo.add(new PostInfo(	4891	,"	Toreby L	"));
        listeMedPostInfo.add(new PostInfo(	4892	,"	Kettinge	"));
        listeMedPostInfo.add(new PostInfo(	4894	,"	Øster Ulslev	"));
        listeMedPostInfo.add(new PostInfo(	4895	,"	Errindlev	"));
        listeMedPostInfo.add(new PostInfo(	4900	,"	Nakskov	"));
        listeMedPostInfo.add(new PostInfo(	4912	,"	Harpelunde	"));
        listeMedPostInfo.add(new PostInfo(	4913	,"	Horslunde	"));
        listeMedPostInfo.add(new PostInfo(	4920	,"	Søllested	"));
        listeMedPostInfo.add(new PostInfo(	4930	,"	Maribo	"));
        listeMedPostInfo.add(new PostInfo(	4941	,"	Bandholm	"));
        listeMedPostInfo.add(new PostInfo(	4943	,"	Torrig L	"));
        listeMedPostInfo.add(new PostInfo(	4944	,"	Fejø	"));
        listeMedPostInfo.add(new PostInfo(	4951	,"	Nørreballe	"));
        listeMedPostInfo.add(new PostInfo(	4952	,"	Stokkemarke	"));
        listeMedPostInfo.add(new PostInfo(	4953	,"	Vesterborg	"));
        listeMedPostInfo.add(new PostInfo(	4960	,"	Holeby	"));
        listeMedPostInfo.add(new PostInfo(	4970	,"	Rødby	"));
        listeMedPostInfo.add(new PostInfo(	4983	,"	Dannemare	"));
        listeMedPostInfo.add(new PostInfo(	4990	,"	Sakskøbing	"));
        listeMedPostInfo.add(new PostInfo(	5000	,"	Odense C	"));
        listeMedPostInfo.add(new PostInfo(	5200	,"	Odense V	"));
        listeMedPostInfo.add(new PostInfo(	5210	,"	Odense NV	"));
        listeMedPostInfo.add(new PostInfo(	5220	,"	Odense SØ	"));
        listeMedPostInfo.add(new PostInfo(	5230	,"	Odense M	"));
        listeMedPostInfo.add(new PostInfo(	5240	,"	Odense NØ	"));
        listeMedPostInfo.add(new PostInfo(	5250	,"	Odense SV	"));
        listeMedPostInfo.add(new PostInfo(	5260	,"	Odense S	"));
        listeMedPostInfo.add(new PostInfo(	5270	,"	Odense N	"));
        listeMedPostInfo.add(new PostInfo(	5290	,"	Marslev	"));
        listeMedPostInfo.add(new PostInfo(	5300	,"	Kerteminde	"));
        listeMedPostInfo.add(new PostInfo(	5320	,"	Agedrup	"));
        listeMedPostInfo.add(new PostInfo(	5330	,"	Munkebo	"));
        listeMedPostInfo.add(new PostInfo(	5350	,"	Rynkeby	"));
        listeMedPostInfo.add(new PostInfo(	5370	,"	Mesinge	"));
        listeMedPostInfo.add(new PostInfo(	5380	,"	Dalby	"));
        listeMedPostInfo.add(new PostInfo(	5390	,"	Martofte	"));
        listeMedPostInfo.add(new PostInfo(	5400	,"	Bogense	"));
        listeMedPostInfo.add(new PostInfo(	5450	,"	Otterup	"));
        listeMedPostInfo.add(new PostInfo(	5462	,"	Morud	"));
        listeMedPostInfo.add(new PostInfo(	5463	,"	Harndrup	"));
        listeMedPostInfo.add(new PostInfo(	5464	,"	Brenderup Fyn	"));
        listeMedPostInfo.add(new PostInfo(	5466	,"	Asperup	"));
        listeMedPostInfo.add(new PostInfo(	5471	,"	Søndersø	"));
        listeMedPostInfo.add(new PostInfo(	5474	,"	Veflinge	"));
        listeMedPostInfo.add(new PostInfo(	5485	,"	Skamby	"));
        listeMedPostInfo.add(new PostInfo(	5491	,"	Blommenslyst	"));
        listeMedPostInfo.add(new PostInfo(	5492	,"	Vissenbjerg	"));
        listeMedPostInfo.add(new PostInfo(	5500	,"	Middelfart	"));
        listeMedPostInfo.add(new PostInfo(	5540	,"	Ullerslev	"));
        listeMedPostInfo.add(new PostInfo(	5550	,"	Langeskov	"));
        listeMedPostInfo.add(new PostInfo(	5560	,"	Aarup	"));
        listeMedPostInfo.add(new PostInfo(	5580	,"	Nørre Aaby	"));
        listeMedPostInfo.add(new PostInfo(	5591	,"	Gelsted	"));
        listeMedPostInfo.add(new PostInfo(	5592	,"	Ejby	"));
        listeMedPostInfo.add(new PostInfo(	5600	,"	Faaborg	"));
        listeMedPostInfo.add(new PostInfo(	5610	,"	Assens	"));
        listeMedPostInfo.add(new PostInfo(	5620	,"	Glamsbjerg	"));
        listeMedPostInfo.add(new PostInfo(	5631	,"	Ebberup	"));
        listeMedPostInfo.add(new PostInfo(	5642	,"	Millinge	"));
        listeMedPostInfo.add(new PostInfo(	5672	,"	Broby	"));
        listeMedPostInfo.add(new PostInfo(	5683	,"	Haarby	"));
        listeMedPostInfo.add(new PostInfo(	5690	,"	Tommerup	"));
        listeMedPostInfo.add(new PostInfo(	5700	,"	Svendborg	"));
        listeMedPostInfo.add(new PostInfo(	5750	,"	Ringe	"));
        listeMedPostInfo.add(new PostInfo(	5762	,"	Vester Skerninge	"));
        listeMedPostInfo.add(new PostInfo(	5771	,"	Stenstrup	"));
        listeMedPostInfo.add(new PostInfo(	5772	,"	Kværndrup	"));
        listeMedPostInfo.add(new PostInfo(	5792	,"	Årslev	"));
        listeMedPostInfo.add(new PostInfo(	5800	,"	Nyborg	"));
        listeMedPostInfo.add(new PostInfo(	5853	,"	Ørbæk	"));
        listeMedPostInfo.add(new PostInfo(	5854	,"	Gislev	"));
        listeMedPostInfo.add(new PostInfo(	5856	,"	Ryslinge	"));
        listeMedPostInfo.add(new PostInfo(	5863	,"	Ferritslev Fyn	"));
        listeMedPostInfo.add(new PostInfo(	5871	,"	Frørup	"));
        listeMedPostInfo.add(new PostInfo(	5874	,"	Hesselager	"));
        listeMedPostInfo.add(new PostInfo(	5881	,"	Skårup Fyn	"));
        listeMedPostInfo.add(new PostInfo(	5882	,"	Vejstrup	"));
        listeMedPostInfo.add(new PostInfo(	5883	,"	Oure	"));
        listeMedPostInfo.add(new PostInfo(	5884	,"	Gudme	"));
        listeMedPostInfo.add(new PostInfo(	5892	,"	Gudbjerg Sydfyn	"));
        listeMedPostInfo.add(new PostInfo(	5900	,"	Rudkøbing	"));
        listeMedPostInfo.add(new PostInfo(	5932	,"	Humble	"));
        listeMedPostInfo.add(new PostInfo(	5935	,"	Bagenkop	"));
        listeMedPostInfo.add(new PostInfo(	5953	,"	Tranekær	"));
        listeMedPostInfo.add(new PostInfo(	5960	,"	Marstal	"));
        listeMedPostInfo.add(new PostInfo(	5970	,"	Ærøskøbing	"));
        listeMedPostInfo.add(new PostInfo(	5985	,"	Søby Ærø	"));
        listeMedPostInfo.add(new PostInfo(	6000	,"	Kolding	"));
        listeMedPostInfo.add(new PostInfo(	6040	,"	Egtved	"));
        listeMedPostInfo.add(new PostInfo(	6051	,"	Almind	"));
        listeMedPostInfo.add(new PostInfo(	6052	,"	Viuf	"));
        listeMedPostInfo.add(new PostInfo(	6064	,"	Jordrup	"));
        listeMedPostInfo.add(new PostInfo(	6070	,"	Christiansfeld	"));
        listeMedPostInfo.add(new PostInfo(	6091	,"	Bjert	"));
        listeMedPostInfo.add(new PostInfo(	6092	,"	Sønder Stenderup	"));
        listeMedPostInfo.add(new PostInfo(	6093	,"	Sjølund	"));
        listeMedPostInfo.add(new PostInfo(	6094	,"	Hejls	"));
        listeMedPostInfo.add(new PostInfo(	6100	,"	Haderslev	"));
        listeMedPostInfo.add(new PostInfo(	6200	,"	Aabenraa	"));
        listeMedPostInfo.add(new PostInfo(	6230	,"	Rødekro	"));
        listeMedPostInfo.add(new PostInfo(	6240	,"	Løgumkloster	"));
        listeMedPostInfo.add(new PostInfo(	6261	,"	Bredebro	"));
        listeMedPostInfo.add(new PostInfo(	6270	,"	Tønder	"));
        listeMedPostInfo.add(new PostInfo(	6280	,"	Højer	"));
        listeMedPostInfo.add(new PostInfo(	6300	,"	Gråsten	"));
        listeMedPostInfo.add(new PostInfo(	6310	,"	Broager	"));
        listeMedPostInfo.add(new PostInfo(	6320	,"	Egernsund	"));
        listeMedPostInfo.add(new PostInfo(	6330	,"	Padborg	"));
        listeMedPostInfo.add(new PostInfo(	6340	,"	Kruså	"));
        listeMedPostInfo.add(new PostInfo(	6360	,"	Tinglev	"));
        listeMedPostInfo.add(new PostInfo(	6372	,"	Bylderup-Bov	"));
        listeMedPostInfo.add(new PostInfo(	6392	,"	Bolderslev	"));
        listeMedPostInfo.add(new PostInfo(	6400	,"	Sønderborg	"));
        listeMedPostInfo.add(new PostInfo(	6430	,"	Nordborg	"));
        listeMedPostInfo.add(new PostInfo(	6440	,"	Augustenborg	"));
        listeMedPostInfo.add(new PostInfo(	6470	,"	Sydals	"));
        listeMedPostInfo.add(new PostInfo(	6500	,"	Vojens	"));
        listeMedPostInfo.add(new PostInfo(	6510	,"	Gram	"));
        listeMedPostInfo.add(new PostInfo(	6520	,"	Toftlund	"));
        listeMedPostInfo.add(new PostInfo(	6534	,"	Agerskov	"));
        listeMedPostInfo.add(new PostInfo(	6535	,"	Branderup J	"));
        listeMedPostInfo.add(new PostInfo(	6541	,"	Bevtoft	"));
        listeMedPostInfo.add(new PostInfo(	6560	,"	Sommersted	"));
        listeMedPostInfo.add(new PostInfo(	6580	,"	Vamdrup	"));
        listeMedPostInfo.add(new PostInfo(	6600	,"	Vejen	"));
        listeMedPostInfo.add(new PostInfo(	6621	,"	Gesten	"));
        listeMedPostInfo.add(new PostInfo(	6622	,"	Bække	"));
        listeMedPostInfo.add(new PostInfo(	6623	,"	Vorbasse	"));
        listeMedPostInfo.add(new PostInfo(	6630	,"	Rødding	"));
        listeMedPostInfo.add(new PostInfo(	6640	,"	Lunderskov	"));
        listeMedPostInfo.add(new PostInfo(	6650	,"	Brørup	"));
        listeMedPostInfo.add(new PostInfo(	6660	,"	Lintrup	"));
        listeMedPostInfo.add(new PostInfo(	6670	,"	Holsted	"));
        listeMedPostInfo.add(new PostInfo(	6682	,"	Hovborg	"));
        listeMedPostInfo.add(new PostInfo(	6683	,"	Føvling	"));
        listeMedPostInfo.add(new PostInfo(	6690	,"	Gørding	"));
        listeMedPostInfo.add(new PostInfo(	6700	,"	Esbjerg	"));
        listeMedPostInfo.add(new PostInfo(	6705	,"	Esbjerg Ø	"));
        listeMedPostInfo.add(new PostInfo(	6710	,"	Esbjerg V	"));
        listeMedPostInfo.add(new PostInfo(	6715	,"	Esbjerg N	"));
        listeMedPostInfo.add(new PostInfo(	6720	,"	Fanø	"));
        listeMedPostInfo.add(new PostInfo(	6731	,"	Tjæreborg	"));
        listeMedPostInfo.add(new PostInfo(	6740	,"	Bramming	"));
        listeMedPostInfo.add(new PostInfo(	6752	,"	Glejbjerg	"));
        listeMedPostInfo.add(new PostInfo(	6753	,"	Agerbæk	"));
        listeMedPostInfo.add(new PostInfo(	6760	,"	Ribe	"));
        listeMedPostInfo.add(new PostInfo(	6771	,"	Gredstedbro	"));
        listeMedPostInfo.add(new PostInfo(	6780	,"	Skærbæk	"));
        listeMedPostInfo.add(new PostInfo(	6792	,"	Rømø	"));
        listeMedPostInfo.add(new PostInfo(	6800	,"	Varde	"));
        listeMedPostInfo.add(new PostInfo(	6818	,"	Årre	"));
        listeMedPostInfo.add(new PostInfo(	6823	,"	Ansager	"));
        listeMedPostInfo.add(new PostInfo(	6830	,"	Nørre Nebel	"));
        listeMedPostInfo.add(new PostInfo(	6840	,"	Oksbøl	"));
        listeMedPostInfo.add(new PostInfo(	6851	,"	Janderup Vestj	"));
        listeMedPostInfo.add(new PostInfo(	6852	,"	Billum	"));
        listeMedPostInfo.add(new PostInfo(	6853	,"	Vejers Strand	"));
        listeMedPostInfo.add(new PostInfo(	6854	,"	Henne	"));
        listeMedPostInfo.add(new PostInfo(	6855	,"	Outrup	"));
        listeMedPostInfo.add(new PostInfo(	6857	,"	Blåvand	"));
        listeMedPostInfo.add(new PostInfo(	6862	,"	Tistrup	"));
        listeMedPostInfo.add(new PostInfo(	6870	,"	Ølgod	"));
        listeMedPostInfo.add(new PostInfo(	6880	,"	Tarm	"));
        listeMedPostInfo.add(new PostInfo(	6893	,"	Hemmet	"));
        listeMedPostInfo.add(new PostInfo(	6900	,"	Skjern	"));
        listeMedPostInfo.add(new PostInfo(	6920	,"	Videbæk	"));
        listeMedPostInfo.add(new PostInfo(	6933	,"	Kibæk	"));
        listeMedPostInfo.add(new PostInfo(	6940	,"	Lem St	"));
        listeMedPostInfo.add(new PostInfo(	6950	,"	Ringkøbing	"));
        listeMedPostInfo.add(new PostInfo(	6960	,"	Hvide Sande	"));
        listeMedPostInfo.add(new PostInfo(	6971	,"	Spjald	"));
        listeMedPostInfo.add(new PostInfo(	6973	,"	Ørnhøj	"));
        listeMedPostInfo.add(new PostInfo(	6980	,"	Tim	"));
        listeMedPostInfo.add(new PostInfo(	6990	,"	Ulfborg	"));
        listeMedPostInfo.add(new PostInfo(	7000	,"	Fredericia	"));
        listeMedPostInfo.add(new PostInfo(	7007	,"	Fredericia	"));
        listeMedPostInfo.add(new PostInfo(	7080	,"	Børkop	"));
        listeMedPostInfo.add(new PostInfo(	7100	,"	Vejle	"));
        listeMedPostInfo.add(new PostInfo(	7120	,"	Vejle Øst	"));
        listeMedPostInfo.add(new PostInfo(	7130	,"	Juelsminde	"));
        listeMedPostInfo.add(new PostInfo(	7140	,"	Stouby	"));
        listeMedPostInfo.add(new PostInfo(	7150	,"	Barrit	"));
        listeMedPostInfo.add(new PostInfo(	7160	,"	Tørring	"));
        listeMedPostInfo.add(new PostInfo(	7171	,"	Uldum	"));
        listeMedPostInfo.add(new PostInfo(	7173	,"	Vonge	"));
        listeMedPostInfo.add(new PostInfo(	7182	,"	Bredsten	"));
        listeMedPostInfo.add(new PostInfo(	7183	,"	Randbøl	"));
        listeMedPostInfo.add(new PostInfo(	7184	,"	Vandel	"));
        listeMedPostInfo.add(new PostInfo(	7190	,"	Billund	"));
        listeMedPostInfo.add(new PostInfo(	7200	,"	Grindsted	"));
        listeMedPostInfo.add(new PostInfo(	7250	,"	Hejnsvig	"));
        listeMedPostInfo.add(new PostInfo(	7260	,"	Sønder Omme	"));
        listeMedPostInfo.add(new PostInfo(	7270	,"	Stakroge	"));
        listeMedPostInfo.add(new PostInfo(	7280	,"	Sønder Felding	"));
        listeMedPostInfo.add(new PostInfo(	7300	,"	Jelling	"));
        listeMedPostInfo.add(new PostInfo(	7321	,"	Gadbjerg	"));
        listeMedPostInfo.add(new PostInfo(	7323	,"	Give	"));
        listeMedPostInfo.add(new PostInfo(	7330	,"	Brande	"));
        listeMedPostInfo.add(new PostInfo(	7361	,"	Ejstrupholm	"));
        listeMedPostInfo.add(new PostInfo(	7362	,"	Hampen	"));
        listeMedPostInfo.add(new PostInfo(	7400	,"	Herning	"));
        listeMedPostInfo.add(new PostInfo(	7430	,"	Ikast	"));
        listeMedPostInfo.add(new PostInfo(	7441	,"	Bording	"));
        listeMedPostInfo.add(new PostInfo(	7442	,"	Engesvang	"));
        listeMedPostInfo.add(new PostInfo(	7451	,"	Sunds	"));
        listeMedPostInfo.add(new PostInfo(	7470	,"	Karup J	"));
        listeMedPostInfo.add(new PostInfo(	7480	,"	Vildbjerg	"));
        listeMedPostInfo.add(new PostInfo(	7490	,"	Aulum	"));
        listeMedPostInfo.add(new PostInfo(	7500	,"	Holstebro	"));
        listeMedPostInfo.add(new PostInfo(	7540	,"	Haderup	"));
        listeMedPostInfo.add(new PostInfo(	7550	,"	Sørvad	"));
        listeMedPostInfo.add(new PostInfo(	7560	,"	Hjerm	"));
        listeMedPostInfo.add(new PostInfo(	7570	,"	Vemb	"));
        listeMedPostInfo.add(new PostInfo(	7600	,"	Struer	"));
        listeMedPostInfo.add(new PostInfo(	7620	,"	Lemvig	"));
        listeMedPostInfo.add(new PostInfo(	7650	,"	Bøvlingbjerg	"));
        listeMedPostInfo.add(new PostInfo(	7660	,"	Bækmarksbro	"));
        listeMedPostInfo.add(new PostInfo(	7673	,"	Harboøre	"));
        listeMedPostInfo.add(new PostInfo(	7680	,"	Thyborøn	"));
        listeMedPostInfo.add(new PostInfo(	7700	,"	Thisted	"));
        listeMedPostInfo.add(new PostInfo(	7730	,"	Hanstholm	"));
        listeMedPostInfo.add(new PostInfo(	7741	,"	Frøstrup	"));
        listeMedPostInfo.add(new PostInfo(	7742	,"	Vesløs	"));
        listeMedPostInfo.add(new PostInfo(	7752	,"	Snedsted	"));
        listeMedPostInfo.add(new PostInfo(	7755	,"	Bedsted Thy	"));
        listeMedPostInfo.add(new PostInfo(	7760	,"	Hurup Thy	"));
        listeMedPostInfo.add(new PostInfo(	7770	,"	Vestervig	"));
        listeMedPostInfo.add(new PostInfo(	7790	,"	Thyholm	"));
        listeMedPostInfo.add(new PostInfo(	7800	,"	Skive	"));
        listeMedPostInfo.add(new PostInfo(	7830	,"	Vinderup	"));
        listeMedPostInfo.add(new PostInfo(	7840	,"	Højslev	"));
        listeMedPostInfo.add(new PostInfo(	7850	,"	Stoholm Jyll	"));
        listeMedPostInfo.add(new PostInfo(	7860	,"	Spøttrup	"));
        listeMedPostInfo.add(new PostInfo(	7870	,"	Roslev	"));
        listeMedPostInfo.add(new PostInfo(	7884	,"	Fur	"));
        listeMedPostInfo.add(new PostInfo(	7900	,"	Nykøbing M	"));
        listeMedPostInfo.add(new PostInfo(	7950	,"	Erslev	"));
        listeMedPostInfo.add(new PostInfo(	7960	,"	Karby	"));
        listeMedPostInfo.add(new PostInfo(	7970	,"	Redsted M	"));
        listeMedPostInfo.add(new PostInfo(	7980	,"	Vils	"));
        listeMedPostInfo.add(new PostInfo(	7990	,"	Øster Assels	"));
        listeMedPostInfo.add(new PostInfo(	8000	,"	Aarhus C	"));
        listeMedPostInfo.add(new PostInfo(	8200	,"	Aarhus N	"));
        listeMedPostInfo.add(new PostInfo(	8210	,"	Aarhus V	"));
        listeMedPostInfo.add(new PostInfo(	8220	,"	Brabrand	"));
        listeMedPostInfo.add(new PostInfo(	8230	,"	Åbyhøj	"));
        listeMedPostInfo.add(new PostInfo(	8240	,"	Risskov	"));
        listeMedPostInfo.add(new PostInfo(	8245	,"	Risskov Ø	"));
        listeMedPostInfo.add(new PostInfo(	8250	,"	Egå	"));
        listeMedPostInfo.add(new PostInfo(	8260	,"	Viby J	"));
        listeMedPostInfo.add(new PostInfo(	8270	,"	Højbjerg	"));
        listeMedPostInfo.add(new PostInfo(	8300	,"	Odder	"));
        listeMedPostInfo.add(new PostInfo(	8305	,"	Samsø	"));
        listeMedPostInfo.add(new PostInfo(	8310	,"	Tranbjerg J	"));
        listeMedPostInfo.add(new PostInfo(	8320	,"	Mårslet	"));
        listeMedPostInfo.add(new PostInfo(	8330	,"	Beder	"));
        listeMedPostInfo.add(new PostInfo(	8340	,"	Malling	"));
        listeMedPostInfo.add(new PostInfo(	8350	,"	Hundslund	"));
        listeMedPostInfo.add(new PostInfo(	8355	,"	Solbjerg	"));
        listeMedPostInfo.add(new PostInfo(	8361	,"	Hasselager	"));
        listeMedPostInfo.add(new PostInfo(	8362	,"	Hørning	"));
        listeMedPostInfo.add(new PostInfo(	8370	,"	Hadsten	"));
        listeMedPostInfo.add(new PostInfo(	8380	,"	Trige	"));
        listeMedPostInfo.add(new PostInfo(	8381	,"	Tilst	"));
        listeMedPostInfo.add(new PostInfo(	8382	,"	Hinnerup	"));
        listeMedPostInfo.add(new PostInfo(	8400	,"	Ebeltoft	"));
        listeMedPostInfo.add(new PostInfo(	8410	,"	Rønde	"));
        listeMedPostInfo.add(new PostInfo(	8420	,"	Knebel	"));
        listeMedPostInfo.add(new PostInfo(	8444	,"	Balle	"));
        listeMedPostInfo.add(new PostInfo(	8450	,"	Hammel	"));
        listeMedPostInfo.add(new PostInfo(	8462	,"	Harlev J	"));
        listeMedPostInfo.add(new PostInfo(	8464	,"	Galten	"));
        listeMedPostInfo.add(new PostInfo(	8471	,"	Sabro	"));
        listeMedPostInfo.add(new PostInfo(	8472	,"	Sporup	"));
        listeMedPostInfo.add(new PostInfo(	8500	,"	Grenaa	"));
        listeMedPostInfo.add(new PostInfo(	8520	,"	Lystrup	"));
        listeMedPostInfo.add(new PostInfo(	8530	,"	Hjortshøj	"));
        listeMedPostInfo.add(new PostInfo(	8541	,"	Skødstrup	"));
        listeMedPostInfo.add(new PostInfo(	8543	,"	Hornslet	"));
        listeMedPostInfo.add(new PostInfo(	8544	,"	Mørke	"));
        listeMedPostInfo.add(new PostInfo(	8550	,"	Ryomgård	"));
        listeMedPostInfo.add(new PostInfo(	8560	,"	Kolind	"));
        listeMedPostInfo.add(new PostInfo(	8570	,"	Trustrup	"));
        listeMedPostInfo.add(new PostInfo(	8581	,"	Nimtofte	"));
        listeMedPostInfo.add(new PostInfo(	8585	,"	Glesborg	"));
        listeMedPostInfo.add(new PostInfo(	8586	,"	Ørum Djurs	"));
        listeMedPostInfo.add(new PostInfo(	8592	,"	Anholt	"));
        listeMedPostInfo.add(new PostInfo(	8600	,"	Silkeborg	"));
        listeMedPostInfo.add(new PostInfo(	8620	,"	Kjellerup	"));
        listeMedPostInfo.add(new PostInfo(	8632	,"	Lemming	"));
        listeMedPostInfo.add(new PostInfo(	8641	,"	Sorring	"));
        listeMedPostInfo.add(new PostInfo(	8643	,"	Ans By	"));
        listeMedPostInfo.add(new PostInfo(	8653	,"	Them	"));
        listeMedPostInfo.add(new PostInfo(	8654	,"	Bryrup	"));
        listeMedPostInfo.add(new PostInfo(	8660	,"	Skanderborg	"));
        listeMedPostInfo.add(new PostInfo(	8670	,"	Låsby	"));
        listeMedPostInfo.add(new PostInfo(	8680	,"	Ry	"));
        listeMedPostInfo.add(new PostInfo(	8700	,"	Horsens	"));
        listeMedPostInfo.add(new PostInfo(	8721	,"	Daugård	"));
        listeMedPostInfo.add(new PostInfo(	8722	,"	Hedensted	"));
        listeMedPostInfo.add(new PostInfo(	8723	,"	Løsning	"));
        listeMedPostInfo.add(new PostInfo(	8732	,"	Hovedgård	"));
        listeMedPostInfo.add(new PostInfo(	8740	,"	Brædstrup	"));
        listeMedPostInfo.add(new PostInfo(	8751	,"	Gedved	"));
        listeMedPostInfo.add(new PostInfo(	8752	,"	Østbirk	"));
        listeMedPostInfo.add(new PostInfo(	8762	,"	Flemming	"));
        listeMedPostInfo.add(new PostInfo(	8763	,"	Rask Mølle	"));
        listeMedPostInfo.add(new PostInfo(	8765	,"	Klovborg	"));
        listeMedPostInfo.add(new PostInfo(	8766	,"	Nørre Snede	"));
        listeMedPostInfo.add(new PostInfo(	8781	,"	Stenderup	"));
        listeMedPostInfo.add(new PostInfo(	8783	,"	Hornsyld	"));
        listeMedPostInfo.add(new PostInfo(	8800	,"	Viborg	"));
        listeMedPostInfo.add(new PostInfo(	8830	,"	Tjele	"));
        listeMedPostInfo.add(new PostInfo(	8831	,"	Løgstrup	"));
        listeMedPostInfo.add(new PostInfo(	8832	,"	Skals	"));
        listeMedPostInfo.add(new PostInfo(	8840	,"	Rødkærsbro	"));
        listeMedPostInfo.add(new PostInfo(	8850	,"	Bjerringbro	"));
        listeMedPostInfo.add(new PostInfo(	8860	,"	Ulstrup	"));
        listeMedPostInfo.add(new PostInfo(	8870	,"	Langå	"));
        listeMedPostInfo.add(new PostInfo(	8881	,"	Thorsø	"));
        listeMedPostInfo.add(new PostInfo(	8882	,"	Fårvang	"));
        listeMedPostInfo.add(new PostInfo(	8883	,"	Gjern	"));
        listeMedPostInfo.add(new PostInfo(	8900	,"	Randers C	"));
        listeMedPostInfo.add(new PostInfo(	8920	,"	Randers NV	"));
        listeMedPostInfo.add(new PostInfo(	8930	,"	Randers NØ	"));
        listeMedPostInfo.add(new PostInfo(	8940	,"	Randers SV	"));
        listeMedPostInfo.add(new PostInfo(	8950	,"	Ørsted	"));
        listeMedPostInfo.add(new PostInfo(	8960	,"	Randers SØ	"));
        listeMedPostInfo.add(new PostInfo(	8961	,"	Allingåbro	"));
        listeMedPostInfo.add(new PostInfo(	8963	,"	Auning	"));
        listeMedPostInfo.add(new PostInfo(	8970	,"	Havndal	"));
        listeMedPostInfo.add(new PostInfo(	8981	,"	Spentrup	"));
        listeMedPostInfo.add(new PostInfo(	8983	,"	Gjerlev J	"));
        listeMedPostInfo.add(new PostInfo(	8990	,"	Fårup	"));
        listeMedPostInfo.add(new PostInfo(	9000	,"	Aalborg	"));
        listeMedPostInfo.add(new PostInfo(	9200	,"	Aalborg SV	"));
        listeMedPostInfo.add(new PostInfo(	9210	,"	Aalborg SØ	"));
        listeMedPostInfo.add(new PostInfo(	9220	,"	Aalborg Øst	"));
        listeMedPostInfo.add(new PostInfo(	9230	,"	Svenstrup J	"));
        listeMedPostInfo.add(new PostInfo(	9240	,"	Nibe	"));
        listeMedPostInfo.add(new PostInfo(	9260	,"	Gistrup	"));
        listeMedPostInfo.add(new PostInfo(	9270	,"	Klarup	"));
        listeMedPostInfo.add(new PostInfo(	9280	,"	Storvorde	"));
        listeMedPostInfo.add(new PostInfo(	9293	,"	Kongerslev	"));
        listeMedPostInfo.add(new PostInfo(	9300	,"	Sæby	"));
        listeMedPostInfo.add(new PostInfo(	9310	,"	Vodskov	"));
        listeMedPostInfo.add(new PostInfo(	9320	,"	Hjallerup	"));
        listeMedPostInfo.add(new PostInfo(	9330	,"	Dronninglund	"));
        listeMedPostInfo.add(new PostInfo(	9340	,"	Asaa	"));
        listeMedPostInfo.add(new PostInfo(	9352	,"	Dybvad	"));
        listeMedPostInfo.add(new PostInfo(	9362	,"	Gandrup	"));
        listeMedPostInfo.add(new PostInfo(	9370	,"	Hals	"));
        listeMedPostInfo.add(new PostInfo(	9380	,"	Vestbjerg	"));
        listeMedPostInfo.add(new PostInfo(	9381	,"	Sulsted	"));
        listeMedPostInfo.add(new PostInfo(	9382	,"	Tylstrup	"));
        listeMedPostInfo.add(new PostInfo(	9400	,"	Nørresundby	"));
        listeMedPostInfo.add(new PostInfo(	9430	,"	Vadum	"));
        listeMedPostInfo.add(new PostInfo(	9440	,"	Aabybro	"));
        listeMedPostInfo.add(new PostInfo(	9460	,"	Brovst	"));
        listeMedPostInfo.add(new PostInfo(	9480	,"	Løkken	"));
        listeMedPostInfo.add(new PostInfo(	9490	,"	Pandrup	"));
        listeMedPostInfo.add(new PostInfo(	9492	,"	Blokhus	"));
        listeMedPostInfo.add(new PostInfo(	9493	,"	Saltum	"));
        listeMedPostInfo.add(new PostInfo(	9500	,"	Hobro	"));
        listeMedPostInfo.add(new PostInfo(	9510	,"	Arden	"));
        listeMedPostInfo.add(new PostInfo(	9520	,"	Skørping	"));
        listeMedPostInfo.add(new PostInfo(	9530	,"	Støvring	"));
        listeMedPostInfo.add(new PostInfo(	9541	,"	Suldrup	"));
        listeMedPostInfo.add(new PostInfo(	9550	,"	Mariager	"));
        listeMedPostInfo.add(new PostInfo(	9560	,"	Hadsund	"));
        listeMedPostInfo.add(new PostInfo(	9574	,"	Bælum	"));
        listeMedPostInfo.add(new PostInfo(	9575	,"	Terndrup	"));
        listeMedPostInfo.add(new PostInfo(	9600	,"	Aars	"));
        listeMedPostInfo.add(new PostInfo(	9610	,"	Nørager	"));
        listeMedPostInfo.add(new PostInfo(	9620	,"	Aalestrup	"));
        listeMedPostInfo.add(new PostInfo(	9631	,"	Gedsted	"));
        listeMedPostInfo.add(new PostInfo(	9632	,"	Møldrup	"));
        listeMedPostInfo.add(new PostInfo(	9640	,"	Farsø	"));
        listeMedPostInfo.add(new PostInfo(	9670	,"	Løgstør	"));
        listeMedPostInfo.add(new PostInfo(	9681	,"	Ranum	"));
        listeMedPostInfo.add(new PostInfo(	9690	,"	Fjerritslev	"));
        listeMedPostInfo.add(new PostInfo(	9700	,"	Brønderslev	"));
        listeMedPostInfo.add(new PostInfo(	9740	,"	Jerslev J	"));
        listeMedPostInfo.add(new PostInfo(	9750	,"	Østervrå	"));
        listeMedPostInfo.add(new PostInfo(	9760	,"	Vrå	"));
        listeMedPostInfo.add(new PostInfo(	9800	,"	Hjørring	"));
        listeMedPostInfo.add(new PostInfo(	9830	,"	Tårs	"));
        listeMedPostInfo.add(new PostInfo(	9850	,"	Hirtshals	"));
        listeMedPostInfo.add(new PostInfo(	9870	,"	Sindal	"));
        listeMedPostInfo.add(new PostInfo(	9881	,"	Bindslev	"));
        listeMedPostInfo.add(new PostInfo(	9900	,"	Frederikshavn	"));
        listeMedPostInfo.add(new PostInfo(	9940	,"	Læsø	"));
        listeMedPostInfo.add(new PostInfo(	9970	,"	Strandby	"));
        listeMedPostInfo.add(new PostInfo(	9981	,"	Jerup	"));
        listeMedPostInfo.add(new PostInfo(	9982	,"	Ålbæk	"));
        listeMedPostInfo.add(new PostInfo(	9990	,"	Skagen	"));


        for (int i = 0; i < listeMedPostInfo.size(); i++) {
            if (listeMedPostInfo.get(i).getPostnummer() == postnummer) {
                System.out.println("Fundet -> " + listeMedPostInfo.get(i).toString());
            }
        }
    }
}
